### ISSUE TITLE
Haddock can't process types-compat-0.1.0

### ISSUE THREAD

**Issue by peti** [philopon/apiary#15]
Haddock from GHC 7.8.4 fails with an internal error trying to process this package:

    Haddock coverage:
      67% (  2 /  3) in 'Data.Proxy.Compat'
      86% ( 19 / 22) in 'Data.Typeable.Compat'
      93% ( 13 / 14) in 'GHC.TypeLits.Compat'
    Warning: Data.Proxy.Compat: could not find link destinations for:
        GHC.Generics.D1Proxy GHC.Generics.C1_0Proxy
    Warning: Data.Typeable.Compat: could not find link destinations for:
        GHC.Arr.STArray GHC.Arr.Array GHC.Generics.D1Proxy GHC.Generics.C1_0Proxy
    haddock: internal error: synifyTyCon: type/data family confusion

**Comment by philopon** [comment]
Thanks for your report:smile:
Please see [types-compat/#1](../../types-compat/issues/1)
