### ISSUE TITLE
Why another Network.Wai.Parse?

### ISSUE THREAD

**Issue by winterland1989** [philopon/apiary#16]
First thank you for making such a great library! It's really easy to use and worked very well.
Recently I came across a issue that i can't get POST request body (both multipart params and url-encode params), i'll bring a minimum case ASAP, during digging i found that you use a customized  Network.Wai.Parse module, what's the purpose then? why not just reuse way-extra package?

**Comment by philopon** [comment]
Wow! thanks for using my library!

Hmm... I cannot remember why I chose ugly way:cold_sweat:
I'll fix it soon!

**Comment by philopon** [comment]
Ok, I fixed it and release v1.4.4.
enjoy:smile:

**Comment by winterland1989** [comment]
Thanks for reply so soon!, i'll test it now :+1:
