### ISSUE TITLE
Support temp file backend 

### ISSUE THREAD

**Issue by winterland1989** [philopon/apiary#19]
Currently the implementation of `getReqBody` doesn't allow use temp file backend to receive file from multipart request body, this often cause memory issues when users try to upload a large file, i'd like to add temp file support and some request size limit functions, but i'm trying to figure out a better interface, what do you think about this?

```haskell
getReqBody :: MonadIO m => ActionT exts prms m RequestBody
getReqBody = ActionT $ \_ e s c -> case actionReqBody s of
    ...
  where
    sink con typ body = do
        (p, f) <- P.sinkRequestBody P.lbsBackEnd typ body
        return $ con p (map convFile f)
  ...
```

Another issue is that `param` rely on `getReqBody` becasue it have to match parameters within body, if i didn't understand `getReqBody` wrong, then every `param` call will have to unpack `actionReqBody` and a `Just` constructor, because `IO` are under our monad stack, is that right?

**Comment by winterland1989** [comment]
Now i have a concrete plan for tackle this, i propose following changes:

+ Add a `maxFileSize` field to ApiaryConfig, which use to controll when to stop receiving file.

+ Use template file backend by default, add field `isPartial` and `filePath` to `Data.Apiary.Param.File`, remove `fileContent` field, and use `isPartial` to mark file we stop receiving.

The main motivation for using template file backend is that, as long as user can upload files, it's also unsafe to save them in memory, since this can lead crash if traffic if high enough.

Are there changes sounds reasonable to you? i'd like to pull a request for this : )

**Comment by philopon** [comment]
Thanks for your mention!
I understood temp file, but I cannot imagined good API, so I had delayed it.
So, I welcome this issue!

> Another issue is that param rely on getReqBody becasue it ~

Oh... It seems right. Would you write small reproduction code and open new issue?

> Add a `maxFileSize` field to ApiaryConfig, which use to controll when to stop receiving file.

[`wai-extra`](http://haddock.stackage.org/lts-5.8/wai-extra-3.0.14.1/Network-Wai-Parse.html) don't provide file size information, so I suggest to add upper limit of whole request body size to guard large file attack (add file size counter to `requestBody :: IO ByteString`).

> Use template file backend by default ~

Hmm... Some PaaS cannot use temporary file, so we must be careful to apply this change.
I prefer to provide function to get request body as temp file.

**Comment by winterland1989** [comment]
> Hmm... Some PaaS cannot use temporary file, so we must be careful to apply this change.
I prefer to provide function to get request body as temp file.

Yes, now i'm agree with you on this, `ApiaryConfig` in my W.I.P code are something like this: 

```haskell
data ApiaryConfig = ApiaryConfig
    { -- | call when no handler matched.
      notFound            :: Wai.Application
      -- | used unless call 'status' function.
    , defaultStatus       :: HTTP.Status
      -- | initial headers.
    , defaultHeaders      :: HTTP.ResponseHeaders
    , defaultContentType  :: S.ByteString
    , failStatus          :: HTTP.Status
    , failHeaders         :: HTTP.ResponseHeaders
      -- | maximum request size.
    , maxRequestSize      :: Word64
      -- | where to store upload file.
      -- default to 'Nothing', which saves file content in memory.
    , uploadFilePath      :: Just FilePath
      -- | used by 'Control.Monad.Apiary.Filter.root' filter.
    , rootPattern         :: [T.Text]
    , mimeType            :: FilePath -> S.ByteString
    }
```

Default to `Nothing` as  `uploadFilePath` will be a back-compatible change, i also change `File` datatype to a sum type to hold file in memory or on disk:

```haskell
data File
    = FileInMem {
        fileParameter   :: S.ByteString
        , fileName        :: S.ByteString
        , fileContentType :: S.ByteString
        , fileContent     :: L.ByteString
        }
    | FileTemp {
          fileParameter   :: S.ByteString
        , fileName        :: S.ByteString
        , fileContentType :: S.ByteString
        , filePath        :: FilePath
        }
    deriving (Show, Eq, Typeable)
```

> wai-extra don't provide file size information, so I suggest to add upper limit of whole request body size to guard large file attack (add file size counter to requestBody :: IO ByteString).

I think `getReqBody` is a good place to add size check, we can write a custom sink function to accumulate request body, if request body is off limit, we respond client with 413 status code, is a custom hook necessary here?

As the `actionReqBody` unpacking, i realise it's necessary since inside `ActionT`, request are parsed when needed, some framework(namely Spock) do request parsing eagerly so redirecting can be avoided. This's a design choice and i think it's ok to keep current behaviour, after all a redirection is not that expensive compared to all the parsing work.

**Comment by winterland1989** [comment]
I'm adding request size check to wait-extra with this pr: https://github.com/yesodweb/wai/pull/525, if it get merged, we can bump wad-extra version and use that utility to guard off-limit request.

**Comment by philopon** [comment]
Thank you for your PR!
