### ISSUE TITLE
Simplify ApiaryWriter, add methods to leverage Wai.Application

### ISSUE THREAD

**Issue by winterland1989** [philopon/apiary#20]
Currently `ApiaryT` can accumulating `middleware` using `middleware` function, but `middleware` isn't adding `middleware` to particular route, but rather to the whole application. because it's added via `Monoid` instance of `ApiaryWriter`, this can lead confusion, so i propose let's remove `middleware` and make a simpler `ApiaryWriter`, add functions like `runApiary / runApiaryWith`:

```haskell
getApiaryWith :: Monad m => Initializer m [] exts -> ApiaryConfig -> ApiaryT exts [] IO m () -> m Application
getApiary :: Monad m => ApiaryConfig -> ApiaryT [] [] IO m () -> m Application
```

So users can add middlerware at `Application` level as they wish. I would also like to supply a function to mount an `Application` to a certain route like this:

```haskell
application :: Monad actM => Application -> ApiaryT exts prms actM m ()
```

It can be used with package like `wai-app-static` or any other packages supplying `Application`. 

Does this plan sounds reasonable to you? i will be very happy to make pull request.

**Comment by philopon** [comment]
merged
