### ISSUE TITLE
Missing files for test suite

### ISSUE THREAD

**Issue by snoyberg** [philopon/apiary#23]
```
    multipart request body
      multipart test:                 FAIL
        Exception: ./tests/dalvik-request: openBinaryFile: does not exist (No such file or directory)
      multipart test:                 FAIL
        Exception: ./tests/dalvik-request: openBinaryFile: does not exist (No such file or directory)
```

**Comment by winterland1989** [comment]
Oh it's because file `dalvik-request` are under `./test` folder from repo's root folder. So can you tell me how do you run above test? run `cabal test` inside repo's root seems fine. B.T.W do you know a way not to hard code test file path?

**Comment by snoyberg** [comment]
If you make an sdist tarball and then unpack it, running the tests should fail. You'll need to add the files to extra-source-files in the .cabal file. If you use the Stack-recommended Travis configuration or Herbert's multi-GHC config, it will test this for you.

I wouldn't bother avoiding hard coding the test file path, just make sure it's included in the sdist.

**Comment by winterland1989** [comment]
Ah, i forget to add `dalvik-request` under `extra-source-files`, so cabal didn't include it in the tar ball, i have uploaded a new tar ball, if you still have issue with test please reopen : )
