### ISSUE TITLE
GHC 8 support 

### ISSUE THREAD

**Issue by winterland1989** [philopon/apiary#25]
Since [ghc 8.0.1 has been released](https://www.haskell.org/ghc/download_ghc_8_0_1), i'd like to:
- start to migrate some code, make sure library can be compiled with base 4.9.
- drop ghc 7.6 support. namely cleaning up web-routing 's code.
- leverage new ghc features with back-compatibility.

The new visible type application extension can be used to eliminate varieties usage of `Proxy`, for example, the filter combinators:

``` haskell
    [key|name|] =: pLazyByteString
```

can be replaced by something like this:

``` haskell
    -- eliminate all proxies  
    kv @"name" @LazyByteString
    -- keep the TypeLit proxy
    [key|name|] @LazyByteString
```

I think a type family like `[key|name|] :: KV LazyByteString` will be enough to provide back-compatibility, but i'm really not sure. Iet's start a discussion on this!

**Comment by philopon** [comment]
> ``` .hs
> -- eliminate all proxies  
> kv @"name" @LazyByteString
> ```

It seems good!

What do you think about optional (, many, some, and so on) parameter?

``` .hs
[key|name|] =?: pLazyByteString -- current
optional @"name" @LazyByteString -- using specific function? or any other idea?
```

**Comment by winterland1989** [comment]
FYI, i copy your `Store` and `Dict` from web-rounting into a seperate package: https://github.com/winterland1989/hetero-dict, cleaned up code and fix GHC 8 compile, tests is on the way, the reason doing so is that:
- We can reuse `Dict` data structure to make `Extension` faster, currently `Extension` is a HList like structure, so i assume access a particular extension is O(m) time? Maybe i'm wrong here : )
- The extension system is a small extensible effect system tailored for web server, i think `Dict` will be quite useful in other extensible effect package too, for example: http://hackage.haskell.org/package/multistate-0.7.1.1.

**Comment by winterland1989** [comment]
BTW， i am woking a apiary patch，would me mind me move the rest bits of web-routing into apiary code base？

**Comment by philopon** [comment]
Sorry for my late reply. 😨 

> hetero-dict

It seems good!

> O(m)

I think so too, but I remember that some benchmark show more fast order (I lost it code, sorry). maybe optimization worked.

> The extension system is a small extensible

I think so too. I welcome more extensible extension system!

> BTW， i am woking a apiary patch，would me mind me move the rest bits of web-routing into apiary code base？

I don't care it.

**Comment by winterland1989** [comment]
Done
